### ISSUE TITLE
Example how to use with Kubernetes plugin

### ISSUE THREAD

**Issue by ivankatliarchuk** [lsegal/jenkins-codebuilder-plugin#4]
Hi. 
Interesting plugin and idea behind it as well. 
Single questions:
- Is there is an example of how to use plugin within the Kubernetes? It is a quite common to use case to spin up Jenkins in Kubernetes behind a proxy and quite cool to move some heavy loads away from K8s.

**Comment by lsegal** [comment]
The official repo for this is now [jenkinsci/codebuilder-cloud-plugin](https://github.com/jenkinsci/codebuilder-cloud-plugin). Please re-open this issue there (I'm unable to transfer across orgs).
