### ISSUE TITLE
not using compute type entered in UI

### ISSUE THREAD

**Issue by gferreri** [lsegal/jenkins-codebuilder-plugin#5]
The compute type option specified in the Jenkins UI configuration is not honored when executing this plugin.

Also, the fields in the UI are all reset to defaults when the config UI initially renders.

**Comment by gdams** [comment]
this is fixed by https://github.com/jenkinsci/codebuilder-cloud-plugin/pull/3

**Comment by lsegal** [comment]
Fixed in the other repo.
