### ISSUE TITLE
Support for runtime-versions.

### ISSUE THREAD

**Issue by fimbulvetr** [lsegal/jenkins-codebuilder-plugin#6]
In order to use a newer codebuild image (i.e. anything recent and not unsupported), when launching the buildspec, it must contain a runtime-version declaration, as documented here:

https://docs.aws.amazon.com/codebuild/latest/userguide/sample-runtime-versions.html

However, this plugin [does not send such a declaration](https://github.com/lsegal/jenkins-codebuilder-plugin/blob/75982395317f05a80ffb2ae740d25a95e9dfef57/src/main/java/dev/lsegal/jenkins/codebuilder/CodeBuilderLauncher.java#L90), nor does it seem like it's possible to send one. Can we add support for this? Unfortunately, the standard image shipped by this plugin does not make it possible to build various versions of software, and the standard images shipped by amazon need the runtime-version declaration. This means anyone using this plugin that needs an image with anything other than what this plugin ships needs to use an image that's not blessed by amazon.

**Comment by lsegal** [comment]
The official repo for this is now [jenkinsci/codebuilder-cloud-plugin](https://github.com/jenkinsci/codebuilder-cloud-plugin). Please re-open this issue there (I'm unable to transfer across orgs).
