### ISSUE TITLE
Add support for multiple labels

### ISSUE THREAD

**Issue by gdams** [lsegal/jenkins-codebuilder-plugin#7]
Currently, the plugin only supports 1 label. This is difficult with large CI systems where we have multiple labels (lnux, x64, build, gcc) etc.

We've also used the Orka plugin (https://plugins.jenkins.io/macstadium-orka/) and this does support multiple labels so I imagine the code will be similar.

Thanks!

**Comment by lsegal** [comment]
The official repo for this is now [jenkinsci/codebuilder-cloud-plugin](https://github.com/jenkinsci/codebuilder-cloud-plugin). Please re-open this issue there (I'm unable to transfer across orgs).
